version: "3"
services:
    dns-viewer:
        container_name: "dns-viewer"
        image: elyspio/dns-viewer
        volumes:
            - "./config/front/conf.js:/back/wwwroot/conf.js"
            - "./config/back/appsettings.json:/back/appsettings.json"
            - "/etc/dnsmasq.d/entries.conf:/app/entries.conf"
        networks:
            - external
            - dns-viewer
        labels:
            - "traefik.enable=true"
            - "traefik.docker.network=external"
            - "traefik.http.middlewares.dns-viewer-prefix.stripprefix.prefixes=/dns"
            - "traefik.http.routers.dns-viewer.middlewares=dns-viewer-prefix@docker"
            - "traefik.http.routers.dns-viewer.rule=PathPrefix(`/dns`)"
            - "traefik.http.services.dns-viewer.loadbalancer.server.port=4000"
            - "traefik.http.routers.dns-viewer.entrypoints=external"

networks:
    dns-viewer:
        name: dns-viewer
    internal:
        external: true
    external:
        external: true
